'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.42000
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System.Xml.Serialization

'
'此源代码由 xsd 自动生成, Version=4.6.1055.0。
'

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://tempuri.org/XMLSchema_EOLT.xsd"),  _
 System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://tempuri.org/XMLSchema_EOLT.xsd", IsNullable:=false)>  _
Partial Public Class Test_Result

    Private unitField() As UnitType

    Private stationNumberField As String

    Private operatorNumberField As String

    Private workOrderNumberField As String

    Private productNumberField As String

    Private programNameField As String

    Private dUTDateTimeStartField As Date

    Private dUTDateTimeEndField As Date

    Private testTimeField As Integer

    Public Sub New()
        MyBase.New
        Me.testTimeField = 0
    End Sub

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("Unit")>
    Public Property Unit() As UnitType()
        Get
            Return Me.unitField
        End Get
        Set
            Me.unitField = Value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property StationNumber() As String
        Get
            Return Me.stationNumberField
        End Get
        Set
            Me.stationNumberField = Value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property OperatorNumber() As String
        Get
            Return Me.operatorNumberField
        End Get
        Set
            Me.operatorNumberField = Value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property WorkOrderNumber() As String
        Get
            Return Me.workOrderNumberField
        End Get
        Set
            Me.workOrderNumberField = Value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property ProductNumber() As String
        Get
            Return Me.productNumberField
        End Get
        Set
            Me.productNumberField = Value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property ProgramName() As String
        Get
            Return Me.programNameField
        End Get
        Set
            Me.programNameField = Value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property DUTDateTimeStart() As Date
        Get
            Return Me.dUTDateTimeStartField
        End Get
        Set
            Me.dUTDateTimeStartField = Value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property DUTDateTimeEnd() As Date
        Get
            Return Me.dUTDateTimeEndField
        End Get
        Set
            Me.dUTDateTimeEndField = Value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute(),
     System.ComponentModel.DefaultValueAttribute(0)>
    Public Property TestTime() As Integer
        Get
            Return Me.testTimeField
        End Get
        Set
            Me.testTimeField = Value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/XMLSchema_EOLT.xsd")>
Partial Public Class UnitType

    Private measurementField() As MeasurementType

    Private fSMeasurementField() As FSMeasurementType

    Private laserDMCField As String

    Private serialNumberField As String

    Private retryCountField As Integer

    Private stationField As Integer

    Private fixtureIDField As Integer

    Private statusField As UnitStatus

    Private testTimeStartField As Date

    Private testTimeEndField As Date

    Private unitTestTimeField As Integer

    Private tESTMODEField As TestMode

    Private tESTMODEFieldSpecified As Boolean

    Public Sub New()
        MyBase.New
        Me.retryCountField = 1
        Me.fixtureIDField = 0
        Me.unitTestTimeField = 0
    End Sub

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("Measurement")>
    Public Property Measurement() As MeasurementType()
        Get
            Return Me.measurementField
        End Get
        Set
            Me.measurementField = Value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("FSMeasurement")>
    Public Property FSMeasurement() As FSMeasurementType()
        Get
            Return Me.fSMeasurementField
        End Get
        Set
            Me.fSMeasurementField = Value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property LaserDMC() As String
        Get
            Return Me.laserDMCField
        End Get
        Set
            Me.laserDMCField = Value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property SerialNumber() As String
        Get
            Return Me.serialNumberField
        End Get
        Set
            Me.serialNumberField = Value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute(),
     System.ComponentModel.DefaultValueAttribute(1)>
    Public Property RetryCount() As Integer
        Get
            Return Me.retryCountField
        End Get
        Set
            Me.retryCountField = Value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property Station() As Integer
        Get
            Return Me.stationField
        End Get
        Set
            Me.stationField = Value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute(),
     System.ComponentModel.DefaultValueAttribute(0)>
    Public Property FixtureID() As Integer
        Get
            Return Me.fixtureIDField
        End Get
        Set
            Me.fixtureIDField = Value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property Status() As UnitStatus
        Get
            Return Me.statusField
        End Get
        Set
            Me.statusField = Value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property TestTimeStart() As Date
        Get
            Return Me.testTimeStartField
        End Get
        Set
            Me.testTimeStartField = Value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property TestTimeEnd() As Date
        Get
            Return Me.testTimeEndField
        End Get
        Set
            Me.testTimeEndField = Value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute(),
     System.ComponentModel.DefaultValueAttribute(0)>
    Public Property UnitTestTime() As Integer
        Get
            Return Me.unitTestTimeField
        End Get
        Set
            Me.unitTestTimeField = Value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property TESTMODE() As TestMode
        Get
            Return Me.tESTMODEField
        End Get
        Set
            Me.tESTMODEField = Value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>
    Public Property TESTMODESpecified() As Boolean
        Get
            Return Me.tESTMODEFieldSpecified
        End Get
        Set
            Me.tESTMODEFieldSpecified = Value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/XMLSchema_EOLT.xsd")>
Partial Public Class MeasurementType

    Private stepNumberField As Short

    Private stepNumberFieldSpecified As Boolean

    Private nameField As String

    Private maxField As String

    Private minField As String

    Private valueField As String

    Private unitField As String

    Private statusCodeField As MeasurementStatus

    Private dateTimeStartField As Date

    Private dateTimeStartFieldSpecified As Boolean

    Private dateTimeEndField As Date

    Private dateTimeEndFieldSpecified As Boolean

    Private measurementTestTimeField As Integer

    Public Sub New()
        MyBase.New
        Me.measurementTestTimeField = 0
    End Sub

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property StepNumber() As Short
        Get
            Return Me.stepNumberField
        End Get
        Set
            Me.stepNumberField = Value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>
    Public Property StepNumberSpecified() As Boolean
        Get
            Return Me.stepNumberFieldSpecified
        End Get
        Set
            Me.stepNumberFieldSpecified = Value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property Name() As String
        Get
            Return Me.nameField
        End Get
        Set
            Me.nameField = Value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property Max() As String
        Get
            Return Me.maxField
        End Get
        Set
            Me.maxField = Value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property Min() As String
        Get
            Return Me.minField
        End Get
        Set
            Me.minField = Value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property Value() As String
        Get
            Return Me.valueField
        End Get
        Set
            Me.valueField = Value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property Unit() As String
        Get
            Return Me.unitField
        End Get
        Set
            Me.unitField = Value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property StatusCode() As MeasurementStatus
        Get
            Return Me.statusCodeField
        End Get
        Set
            Me.statusCodeField = Value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property DateTimeStart() As Date
        Get
            Return Me.dateTimeStartField
        End Get
        Set
            Me.dateTimeStartField = Value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>
    Public Property DateTimeStartSpecified() As Boolean
        Get
            Return Me.dateTimeStartFieldSpecified
        End Get
        Set
            Me.dateTimeStartFieldSpecified = Value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property DateTimeEnd() As Date
        Get
            Return Me.dateTimeEndField
        End Get
        Set
            Me.dateTimeEndField = Value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>
    Public Property DateTimeEndSpecified() As Boolean
        Get
            Return Me.dateTimeEndFieldSpecified
        End Get
        Set
            Me.dateTimeEndFieldSpecified = Value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute(),
     System.ComponentModel.DefaultValueAttribute(0)>
    Public Property MeasurementTestTime() As Integer
        Get
            Return Me.measurementTestTimeField
        End Get
        Set
            Me.measurementTestTimeField = Value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),
 System.SerializableAttribute(),
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/XMLSchema_EOLT.xsd")>
Public Enum MeasurementStatus

    '''<remarks/>
    WaitforTest

    '''<remarks/>
    Testing

    '''<remarks/>
    PASS

    '''<remarks/>
    FAIL

    '''<remarks/>
    [Error]

    '''<remarks/>
    NotTested

    '''<remarks/>
    Disabled

    '''<remarks/>
    Unknown

    '''<remarks/>
    NotCoherent

    '''<remarks/>
    NotValueCheck

End Enum

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/XMLSchema_EOLT.xsd")>
Partial Public Class FSMeasurementType

    Private keyNameField As String

    Private forceField As Double

    Private forceFieldSpecified As Boolean

    Private strokeField As Double

    Private strokeFieldSpecified As Boolean

    Private switchField As Integer

    Private switchFieldSpecified As Boolean

    Private remarkField As String

    Private startTimeField As Date

    Private startTimeFieldSpecified As Boolean

    Private idField As Long

    Private idFieldSpecified As Boolean

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property KeyName() As String
        Get
            Return Me.keyNameField
        End Get
        Set
            Me.keyNameField = Value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property Force() As Double
        Get
            Return Me.forceField
        End Get
        Set
            Me.forceField = Value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>
    Public Property ForceSpecified() As Boolean
        Get
            Return Me.forceFieldSpecified
        End Get
        Set
            Me.forceFieldSpecified = Value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property Stroke() As Double
        Get
            Return Me.strokeField
        End Get
        Set
            Me.strokeField = Value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>
    Public Property StrokeSpecified() As Boolean
        Get
            Return Me.strokeFieldSpecified
        End Get
        Set
            Me.strokeFieldSpecified = Value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property Switch() As Integer
        Get
            Return Me.switchField
        End Get
        Set
            Me.switchField = Value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>
    Public Property SwitchSpecified() As Boolean
        Get
            Return Me.switchFieldSpecified
        End Get
        Set
            Me.switchFieldSpecified = Value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property Remark() As String
        Get
            Return Me.remarkField
        End Get
        Set
            Me.remarkField = Value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute(DataType:="time")>
    Public Property StartTime() As Date
        Get
            Return Me.startTimeField
        End Get
        Set
            Me.startTimeField = Value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>
    Public Property StartTimeSpecified() As Boolean
        Get
            Return Me.startTimeFieldSpecified
        End Get
        Set
            Me.startTimeFieldSpecified = Value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property ID() As Long
        Get
            Return Me.idField
        End Get
        Set
            Me.idField = Value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>
    Public Property IDSpecified() As Boolean
        Get
            Return Me.idFieldSpecified
        End Get
        Set
            Me.idFieldSpecified = Value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),
 System.SerializableAttribute(),
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/XMLSchema_EOLT.xsd")>
Public Enum UnitStatus

    '''<remarks/>
    PASS

    '''<remarks/>
    FAIL

    '''<remarks/>
    INTERRUPTED

    '''<remarks/>
    TESTING

    '''<remarks/>
    WAITFORTEST
End Enum

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),  _
 System.SerializableAttribute(),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/XMLSchema_EOLT.xsd")>  _
Public Enum TestMode
    
    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Mass Production")>  _
    MassProduction
    
    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Daily Check")>  _
    DailyCheck
    
    '''<remarks/>
    Unknown
End Enum
